Eventos.WebUi/Models/ErrorViewModel.cs
namespace Eventos.WebUi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Eventos.WebUi/Controllers/CompraController.cs
using Eventos.Domain.DTOs.InputModel;
using Eventos.Domain.DTOs.OutputModel;
using Eventos.Domain.Interfaces.IService;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Eventos.WebUi.Controllers
{
    public class CompraController : Controller
    {
        private readonly IEventoService _eventoService;
        private readonly IUsuarioService _usuarioService;
        private readonly IEventoParticipanteService _eventoParticipanteService;

        public CompraController(IEventoService eventoService,
            IUsuarioService suarioService,
            IEventoParticipanteService eventoParticipanteService)
        {
            _eventoService = eventoService;
            _usuarioService = suarioService;
            _eventoParticipanteService = eventoParticipanteService;
        }

        public async Task<IActionResult> DetalhesCompra(int id, string nome)
        {
            var evento = await _eventoService.BuscarPorId(id);

            var usuario = await _usuarioService.BuscarUsuarioAsync(nome);

            var retorno = new DetalhesVendaOutputModel(evento, usuario);

            return View(retorno);
        }

        public IActionResult Pagamento(ComprarInputModel model)
            => View(model);
        public async Task<IActionResult> Confirmar(ComprarInputModel model)
        {
            await _eventoParticipanteService.ConfirmarParticipacaoAsync(model);

            var usuario = await _usuarioService.BuscarUsuarioPorIdAsync(model.IdUsuario ?? 0);

            return RedirectToAction("Index", "Perfil", new {usuario = usuario.Usuario});
        }
    }
}

Eventos.WebUi/Controllers/EventoController.cs
using Eventos.Domain.DTOs.InputModel;
using Eventos.Domain.DTOs.OutputModel;
using Eventos.Domain.Enums;
using Eventos.Domain.Interfaces.IService;
using Eventos.WebUi.Resoucer;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Eventos.WebUi.Controllers
{
    public class EventoController : Controller
    {
        private readonly IEventoService _eventoService;
        private readonly ILogadoService _logadoService;
        private readonly IUsuarioService _usuarioService;

        public EventoController(IEventoService eventoService,
            ILogadoService logadoService,
            IUsuarioService usuarioService)
        {
            _eventoService = eventoService;
            _logadoService = logadoService;
            _usuarioService = usuarioService;
        }

        //Telas
        public async Task<IActionResult> Index(CategoriaEnum? categoria)
        {
            var retorno = await _logadoService.VerificarSeLogadoAsync();

            var usuario = await _usuarioService.BuscarUsuarioAsync(retorno);

            if (usuario == null)
                usuario = new UsuarioOutputModel { Id = null };

            ViewData["Usuario"] = retorno;

            return View(await _eventoService.BuscarTodos(categoria, usuario.Id));
        }

        public IActionResult Login()
            => View();

        public IActionResult AdicionarEvento(int? idUsuario)
            => View(new AdicionarEventoInputModel { IdUsuarioOrganizador = idUsuario ?? 10 });

        //Ações
        [HttpPost]
        public async Task<IActionResult> CadastrarEvento(AdicionarEventoInputModel model)
        {
            await _eventoService.AdicionarEvento(model);
            var usuario = await _usuarioService.BuscarUsuarioPorIdAsync(model.IdUsuarioOrganizador);
            return RedirectToAction("Index", "Perfil", new { usuario = usuario.Usuario });
        }

        //Login
        public async Task<IActionResult> Logout()
        {
            var retorno = await _logadoService.DeslogarAsync();

            ViewData["Usuario"] = retorno;

            return View("Index", await _eventoService.BuscarTodos(null, null));
        }

        [HttpPost]
        public async Task<IActionResult> Logar(LoginInputModel model)
        {
            var usuario = await _eventoService.LoginValidoAsync(model);

            if (usuario == null)
            {
                ViewData["Error"] = ServiceResources.UsuarioSenhaInvalidos;

                return View("Login");
            }

            await _logadoService.Logar(usuario.Usuario);

            ViewData["Usuario"] = usuario.Usuario;

            return View("Index", await _eventoService.BuscarTodos(null, usuario.Id));
        }


        //Eventos
        public async Task<IActionResult> CancelarEvento(int usuario, int idEvento)
        {
            await _eventoService.CancelarEventoAsync(idEvento, usuario);

            return RedirectToAction("Index", "Perfil", new { idUsuario = usuario });
        }

        public async Task<IActionResult> CancelarParticipacao(int usuario, int idEvento)
        {
            await _eventoService.CancelarParticipacaoEventoAsync(idEvento, usuario);

            return RedirectToAction("Index", "Perfil", new { idUsuario = usuario });
        }
    }
}

Eventos.WebUi/Controllers/PerfilController.cs
using Eventos.Domain.DTOs.OutputModel;
using Eventos.Domain.Interfaces.IService;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Eventos.WebUi.Controllers
{
    public class PerfilController : Controller
    {
        private readonly IPerfilService _perfilService;
        private readonly IUsuarioService _usuarioService;

        public PerfilController(IPerfilService perfilService, IUsuarioService usuarioService)
        {
            _perfilService = perfilService;
            _usuarioService = usuarioService;
        }

        public async Task<IActionResult> Index(string usuario, int? idUsuario)
        {
            var usuarioPorId = new UsuarioOutputModel();

            if (idUsuario != null && string.IsNullOrWhiteSpace(usuario))
            {
                usuarioPorId = await _usuarioService.BuscarUsuarioPorIdAsync(idUsuario ?? 0);
                usuario = usuarioPorId.Usuario;
            }

            var result = await _perfilService.BuscarInformacoesUsuarioAsync(usuario);

            return View(result);
        }
    }
}

Eventos.WebUi/Controllers/UsuarioController.cs
using Eventos.Domain.DTOs.InputModel;
using Eventos.Domain.Interfaces.IService;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Eventos.WebUi.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        private readonly ILogadoService _logadoService;

        public UsuarioController(IUsuarioService usuarioService, 
            ILogadoService logadoService)
        {
            _usuarioService = usuarioService;
            _logadoService = logadoService;
        }

        public IActionResult Index()
            => View();

        [HttpPost]
        public async Task<IActionResult> Cadastrar(CadastrarUsuarioInputModel model)
        {
            await _usuarioService.CadastrarUsuario(model);

            await _logadoService.Logar(model.Usuario);

            return RedirectToAction("Index","Perfil", new { usuario = model.Usuario});
        }
    }
}

Eventos.WebUi/Views/Compra/DetalhesCompra.cshtml
@using Eventos.Domain.DTOs.InputModel
@using Eventos.Domain.DTOs.OutputModel


@model DetalhesVendaOutputModel

<div class="layout">
    <link rel="stylesheet" href="~/css/Eventos/Conteudo/comprar.css" />
</div>

<section class="conteudo">
    <div class="container-div-form">
        <form class="form-informacoesCompra" asp-form>
            <div class="div-informacoes-usuario">
                <div>
                    <label>Usuario:</label>
                    <label>@Model.Usuario.Usuario</label>
                </div>
                <div>
                    <label>Nome:</label>
                    <label>@Model.Usuario.Nome</label>
                </div>
                <div>
                    <label>Idade:</label>
                    <label>@Model.Usuario.Idade</label>
                </div>
                <div>
                    <label>Data de nascimento:</label>
                    <label>@Model.Usuario.DataNascimento.ToShortDateString()</label>
                </div>
            </div>
            <div class="div-informacoes-evento">
                <img src=@Model.Evento.Imagem />
                <div>
                    <label>Local: </label>
                    <label>@Model.Evento.Nome</label>
                </div>
                <div>
                    <label>Endereço:</label>
                    <label>@Model.Evento.Localidade</label>
                </div>
                <div>
                    <label>Data e Hora:</label>
                    <label>@Model.Evento.DataEHora</label>
                </div>
                <div>
                    <label>Ingressos disponiveis:</label>
                    <label>@Model.Evento.QtdeTotalPessoa</label>
                </div>
                <div>
                    <label>Categoria: </label>
                    <label>@Model.Evento.Categoria</label>
                </div>
                <div>
                    <label>Valor:</label>
                    <label>@Model.Evento.ValorIngresso</label>
                </div>
            </div>
            <div class="div-form-button">
                <input class="layout-ticket-event-dados-buttons-buy pagamento" type="button" value="Pagamento" onclick="location.href='@Url.Action("Pagamento", "Compra", new ComprarInputModel{ IdUsuario = @Model.Usuario.Id, IdEvento = @Model.Evento.Id})'" />
                <input class="layout-ticket-event-dados-buttons-buy cancelar" type="button" value="Cancelar" onclick="location.href='@Url.Action("Index", "Evento")'" />
            </div>
        </form>
    </div>
</section>

<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="~/img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="~/img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="~/img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Compra/Pagamento.cshtml
@using Eventos.Domain.DTOs.InputModel

@model ComprarInputModel

<section class="conteudo">
    <div class="layout">
        <link rel="stylesheet" href="~/css/Eventos/Conteudo/pagamento.css" />
    </div>
    <div class="conteiner-form">
        <form class="form-finalizar-compra" asp-controller="Compra" asp-action="Confirmar" method="post">
            <div class="id-hidden">
                <input hidden asp-for="IdEvento" value="@Model.IdEvento" />
                <input hidden asp-for="IdUsuario" value="@Model.IdUsuario" />
            </div>
            <div class="input-label-div">
                <input type="number" asp-for="Cvc" placeholder="CVC" />
                <div>
                    <label>Parcelamento: </label>
                    <select asp-for="Parcelamento">
                        <option>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                    </select>
                    <label>X </label>
                </div>
            </div>
            <div class="button-div">
                <button class="div-form-button comprar" role="button" type="submit">Comprar</button>
                <input class="div-form-button cancelar" type="button" value="Cancelar" onclick="location.href='@Url.Action("Index", "Evento")'" />
            </div>
        </form>
    </div>
</section>

<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Evento/AdicionarEvento.cshtml
@using Eventos.Domain.DTOs.InputModel
@using Eventos.Domain.Enums

@model AdicionarEventoInputModel

<div class="layout">
    <link rel="stylesheet" href="~/css/Eventos/Conteudo/adicionarEvento.css" />
</div>
<section class="conteudo">
    <div class="div-adcionarEvento">
        <div class="form-background">
            <form class="form-adcionarEvento" asp-controller="Evento" asp-action="CadastrarEvento" method="post">
                <input hidden type="text" asp-for="IdUsuarioOrganizador" value="@Model.IdUsuarioOrganizador" />
                <input type="text" asp-for="Imagem" placeholder="Link imagem" />
                <input type="text" asp-for="Nome" placeholder="Nome do show" />
                <input type="text" asp-for="Rua" placeholder="Rua" />
                <input type="text" asp-for="Numero" placeholder="Numero" />
                <input type="text" asp-for="Cidade" placeholder="Cidade" />
                <input type="text" asp-for="Estado" placeholder="Estado" />
                <input type="text" asp-for="Bairro" placeholder="Bairro" />
                <input type="date" min='2022-07-01' value="2022-07-01" asp-for="Data" placeholder="Dia do evento" />
                <input type="time" asp-for="Hora" placeholder="Hora do evento" />
                <input type="text" asp-for="TamanhoLocal" placeholder="Tamanho do ambiente" />
                <div class="selection-div">
                    <label>Categoria:</label>
                    <select asp-for="Categoria">
                        <option value="@CategoriaEnum.Aniversario">Aniversario</option>
                        <option value="@CategoriaEnum.Compras">Compras</option>
                        <option value="@CategoriaEnum.Fantasia">Fantasia</option>
                        <option value="@CategoriaEnum.Karaoke">Karaoke</option>
                        <option value="@CategoriaEnum.Musica">Musica</option>
                        <option value="@CategoriaEnum.Teatro">Teatro</option>
                    </select>
                </div>
                <input type="text" asp-for="ValorIngresso" placeholder="Valor do ingresso" />
                <div class="div-botoes-addEvento">
                    <button class="botoes-login-registro-button cadastrar" role="button" type="submit">Cadastrar</button>
                    <input class="cancelar" type="button" value="Cancelar" onclick="location.href='@Url.Action("Index", "Perfil", new{idUsuario = @Model.IdUsuarioOrganizador})'" />
                </div>
            </form>
        </div>
    </div>
</section>
<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Evento/Index.cshtml
@using Eventos.Domain.DTOs.OutputModel

@model List<EventoOutputModel>
<div class="layoutIndex">
    <link rel="stylesheet" href="~/css/Eventos/Conteudo/index.css" />
</div>

<section class="conteudo">
    <div class="div-titulo-cabecalho">
        @if (@ViewData["Usuario"].ToString() == "Visitante")
        {
            <h1>Seja bem vindo "@ViewData["Usuario"]"</h1>
            <input type="button" value="Login" onclick="location.href='@Url.Action("Login", "Evento")'">
        }
        else
        {
            <h1>Seja bem vindo "<a asp-controller="Perfil" asp-route-usuario="@ViewData["Usuario"]" asp-action="Index">@ViewData["Usuario"]</a>"</h1>
            <input type="button" value="Logout" onclick="location.href='@Url.Action("Logout", "Evento")'">
        }
    </div>
    <div class="div-dos-eventos">
        @if (Model != null && Model.Any())
        {
            foreach (EventoOutputModel evento in Model)
            {
                <div class="layout-ticket">
                    <div class="layout-ticket-event">
                        <img class="layout-ticket-event-img" src=@evento.Imagem>
                    </div>
                    <div class="layout-ticket-event-dados">
                        <h3>@evento.Nome</h3>
                        <label>Local:</label>
                        <label>@evento.Localidade</label>
                        <label>Data - Horario:</label>
                        <label>@evento.DataEHora</label>
                        <div>
                            <label>Quantidade de ingressos:</label><label>@evento.QtdeTotalPessoa</label>
                        </div>
                        <div class="divCategoria">
                            <label>Categoria:</label>
                            <img class="categoria-imnagem" src="~/img/categorias/@evento.CaminhoImagem">
                        </div>
                        <div class="layout-ticket-event-dados-buttons">
                            @if (@ViewData["Usuario"].ToString() == "Visitante")
                            {
                                <input class="layout-ticket-event-dados-buttons-buy" type="button" disabled value="Comprar" />
                            }
                            else
                            {
                                <input class="layout-ticket-event-dados-buttons-buy" type="button" value="Comprar" onclick="location.href='@Url.Action("DetalhesCompra", "Compra", new{id=@evento.Id, nome=@ViewData["Usuario"].ToString()})'"/>
                            }
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</section>
<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Evento/Login.cshtml
@using Eventos.Domain.DTOs.InputModel
@using Eventos.WebUi.Resoucer

@model LoginInputModel

<section class="conteudo conteudo-login">
    <div class="layout">
        <link rel="stylesheet" href="~/css/Eventos/Conteudo/login.css" />
    </div>
    <div class="div-form-login-registro">
        @if (@ViewData["Error"] != null)
        {
            <div>
                <p class="erroTexto">@ViewData["Error"].ToString()</p>
            </div>
        }
        <form class="form-login-registro" asp-controller="Evento" asp-action="Logar" method="post">
            @if (@ViewData["Error"] != null)
            {
                <input class="form-login-registro-input erroInput" type="text" placeholder="usuario" asp-for="Usuario"  required/>
                <input class="form-login-registro-input erroInput" type="password" placeholder="Senha" asp-for="Password"  required/>
            }
            else
            {
                <input class="form-login-registro-input" type="text" placeholder="usuario" asp-for="Usuario"  required/>
                <input class="form-login-registro-input" type="password" placeholder="Senha" asp-for="Password"  required/>
            }
            <div class="botoes-login-registro">
                <button class="botoes-login-registro-button entrar" role="button" type="submit">Entrar</button>
                <input class="botoes-login-registro-button cadastrar" type="button" onclick="location.href='@Url.Action("Index", "Usuario")'" value="Registrar" />
            </div>
        </form>
    </div>
</section>

<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Perfil/Index.cshtml
@using Eventos.Domain.DTOs.OutputModel

@model EventosUsuarioOutputModel

<div class="layout">
    <link rel="stylesheet" href="~/css/Eventos/Conteudo/perfil.css" />
</div>
<section class="conteudo">
    <div class="detalhes-dados-usuario">
        <div>
            <label>Nome:</label>
            <label>@Model.Usuario.Nome</label>
        </div>
        <div>
            <label>Idade:</label>
            <label>@Model.Usuario.Idade</label>
        </div>
        <div>
            <label>Data de Nascimento:</label>
            <label>@Model.Usuario.DataNascimento.ToShortDateString()</label>
        </div>
        <div>
            <label>Usuario:</label>
            <label>@Model.Usuario.Usuario</label>
        </div>
        <div class="button-return-home-logout">
            <input class="button-return-home" type="button" value="Inicio" onclick="location.href='@Url.Action("Index", "Evento")'"/>
            <input class="button-return-home" type="button" value="Sair" onclick="location.href='@Url.Action("Logout", "Evento")'"/>
        </div>
    </div>
    <div class="div-eventos-usuario">
        <div class="eventos-usuario-sera-participante">
            <h1>Participando: </h1>
            @if (@Model != null)
            {
                foreach (var evento in @Model.EventosParticipante)
                {
                    <div class="layout-ticket">
                        <div class="layout-ticket-event">
                            <img class="layout-ticket-event-img" src=@evento.Imagem>
                        </div>
                        <div class="layout-ticket-event-dados">
                            <label>Local:</label>
                            <label>@evento.Localidade</label>
                            <label>Data - Horario:</label>
                            <label>@evento.DataEHora</label>
                            <div>
                                <label>Quantidade de ingressos:</label><label>@evento.QtdeTotalPessoa</label>
                            </div>
                            <div class="divCategoria">
                                <label>Categoria:</label>
                                <img class="categoria-imnagem" src="~/img/categorias/@evento.CaminhoImagem">
                            </div>
                            <div>
                                <input class="CancelarParticipacao" type="button" value="Cancelar Participação" onclick="location.href='@Url.Action("CancelarParticipacao", "Evento", new{ usuario = @Model.Usuario.Id, idEvento = @evento.Id})'" />
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
        <div class="eventos-usuario-sera-organizador">
            <h1>Organizando: </h1>
            <div class="adicionar-evento">
                <input type="button" value="+" onclick="location.href='@Url.Action("AdicionarEvento", "Evento", new{idUsuario=@Model.Usuario.Id})'" />
            </div>
            @if (@Model != null)
            {
                foreach (var evento in @Model.EventosOrganizador)
                {
                    <div class="layout-ticket">
                        <div class="layout-ticket-event">
                            <img class="layout-ticket-event-img" src=@evento.Imagem>
                        </div>
                        <div class="layout-ticket-event-dados">
                            <label>Local:</label>
                            <label>@evento.Localidade</label>
                            <label>Data - Horario:</label>
                            <label>@evento.DataEHora</label>
                            <div>
                                <label>Quantidade de ingressos:</label><label>@evento.QtdeTotalPessoa</label>
                            </div>
                            <div class="divCategoria">
                                <label>Categoria:</label>
                                <img class="categoria-imnagem" src="~/img/categorias/@evento.CaminhoImagem">
                            </div>
                            <div>
                                <input class="CancelarEvento" type="button" value="Cancelar evento" onclick="location.href='@Url.Action("CancelarEvento", "Evento", new{usuario = @Model.Usuario.Id, idEvento = @evento.Id})'" />
                            </div>
                        </div>
                    </div>
                }
            }

        </div>
    </div>

</section>
<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>

Eventos.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Inicio</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="/css/Eventos/style.css" />
    </head>
    <body>
        <header class="cabecalho">
            <div class="logo-img">
                <img class="logo" src="~/img/logo.png">
                <h1>Eventos-Ticket</h1>
            </div>
        </header>
        @RenderBody()
    </body>
</html>

Eventos.WebUi/Views/Usuario/Index.cshtml
@using Eventos.Domain.DTOs.InputModel

@model CadastrarUsuarioInputModel

<section class="conteudo">
    <div class="layout">
        <link rel="stylesheet" href="~/css/Eventos/Conteudo/registrar.css" />
    </div>
    <div class="form-dados">
        <form class="form-cadastro-usuario" asp-controller="Usuario" asp-action="Cadastrar" method="post">
            <div class="div-dados">
                <div class="dadosUsuario">
                    <label>Nome:</label>
                    <input type="text" asp-for="Nome" required />
                    <label>Idade:</label>
                    <input type="number" asp-for="Idade" required />
                    <label>Data Nascimento:</label>
                    <input type="date" asp-for="DataNascimento" required />
                    <label>Usuario:</label>
                    <input type="text" asp-for="Usuario" required />
                    <label>Password:</label>
                    <input type="text" asp-for="Password" required />
                </div>
                <div class="dadosCartao">
                    <label>Numero do cartao:</label>
                    <input type="text" asp-for="NumeroCartao" required />
                    <label>Nome do cartao:</label>
                    <input type="text" asp-for="NomeCartao" required />
                    <label>CVC:</label>
                    <input type="number" asp-for="Cvc" required />
                    <label>Data de Vencimento:</label>
                    <input type="month" asp-for="DataVencimento" required />
                </div>
            </div>
            <div class="cadastro-finalizar">
                <input class="botoes-login-registro-button cancelar" type="button" onclick="location.href='@Url.Action("Login", "Evento")'" value="Cancelar" />
                <button class="botoes-login-registro-button cadastrar" role="button" type="submit">Cadastrar</button>
            </div>
        </form>
    </div>
</section>
<footer class="rodape">
    <div class="rodape-contato">
        <div class="rodape-contato-div">
            <label>Contato: </label>
        </div>
        <label>
            Mateus - (48) 9 8845-5647
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Ruan - (48) 9 8440-6456
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
        <label>
            Pedro - (47) 9 8809-2450
            <img class="rodape-contato-img" src="../img/whatsapp.svg">
        </label>
    </div>
</footer>